### ISSUE TITLE
In the python3.9 environment, the installation is successful. When importing tacco, TypeError occurs. Do you know the reason?

### ISSUE THREAD

**Issue by baismbaism** [simonwm/tacco#4]
The specific error is as follows:
import tacco as tc

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/baism/anaconda3/envs/TACCO_env/lib/python3.9/site-packages/tacco/__init__.py", line 6, in <module>
    from . import plots as pl
  File "/home/baism/anaconda3/envs/TACCO_env/lib/python3.9/site-packages/tacco/plots/__init__.py", line 6, in <module>
    from ._plots import get_default_colors, mix_base_colors, subplots, scatter, cellsize, frequency_bar, frequency, comparison, compositions, contribution, significances, heatmap, sigmap, co_occurrence, co_occurrence_matrix, annotated_heatmap, annotation_coordinate, dotplot
  File "/home/baism/anaconda3/envs/TACCO_env/lib/python3.9/site-packages/tacco/plots/_plots.py", line 4, in <module>
    import scanpy as sc
  File "/home/baism/anaconda3/envs/TACCO_env/lib/python3.9/site-packages/scanpy/__init__.py", line 17, in <module>
    from . import plotting as pl
  File "/home/baism/anaconda3/envs/TACCO_env/lib/python3.9/site-packages/scanpy/plotting/__init__.py", line 1, in <module>
    from ._anndata import (
  File "/home/baism/anaconda3/envs/TACCO_env/lib/python3.9/site-packages/scanpy/plotting/_anndata.py", line 28, in <module>
    from . import _utils
  File "/home/baism/anaconda3/envs/TACCO_env/lib/python3.9/site-packages/scanpy/plotting/_utils.py", line 36, in <module>
    class _AxesSubplot(Axes, axes.SubplotBase, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

May I ask why this error is reported and how to solve it?

**Comment by simonwm** [comment]
Hi @baismbaism , this error reminds me a lot of the scanpy matplotlib incompatibility for scanpy and matplotlib 3.7: https://github.com/scverse/scanpy/issues/2411 . Did you try a matplotlib below 3.7 or alternatively use a more recent scanpy version like 1.9.2? It looks like this issue is fixed there: https://github.com/scverse/scanpy/tree/1.9.2

**Comment by baismbaism** [comment]
The problem has been solved after your answer, thank you.
